apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "sample-chart.shortname" . }}-config
    labels:
    {{- include "sample-chart.labels" . | nindent 4 }}
data:
  {{ include "sample-chart.config" . }}


