kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "sample-chart.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sample-chart.serviceAccountName" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sample-chart.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "sample-chart.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
