apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-chart.shortname" . }}
  labels:
    {{- include "sample-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.aims8.port }}
      targetPort: aims8-tcp
      protocol: TCP
      name: aims8-tcp
  loadBalancerIP: {{ .Values.service.ip }}
  selector:
    {{- include "sample-chart.selectorLabels" . | nindent 4 }}
